apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: node-cron
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 20
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      completions: 2
      template:
        metadata:
          name: node
        spec:
          containers:
          - name: node-cron
            image: arun15/node-cron-demo:latest
            command: ["node",  "index.js"]
          restartPolicy: Never
